import {
  Championship,
  Team,
  Player,
  Phase,
  Group,
  Match,
  MatchEvent,
  StandingRow,
  Suspension,
  AuditLog,
  NotificationItem,
  User
} from './types';

export const currentUser: User = {
  id: 'usr_admin_1',
  name: 'Rodrigo Silva (Organizador)',
  email: 'rodrigo.organizador@futgestao.com',
  role: 'ADMIN',
  avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
};

export const sampleChampionship: Championship = {
  id: 'champ_1',
  name: 'Copa dos Campeões Fut7 2026',
  slug: 'copa-dos-campeoes-fut7-2026',
  description: 'O maior e mais bem organizado campeonato de futebol 7 society da região. Premiação para campeão, vice, artilheiro, melhor goleiro e craque da galera.',
  startDate: '2026-08-01',
  endDate: '2026-09-30',
  location: 'Arena Park Esportes - Campo 1 & 2',
  address: 'Av. dos Esportes, 1500 - Bairro Central',
  city: 'São Paulo',
  state: 'SP',
  organizerName: 'Rodrigo Silva & Liga Paulista de Fut7',
  organizerPhone: '(11) 98765-4321',
  organizerEmail: 'contato@ligapaulistafut7.com.br',
  logoUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?w=300&auto=format&fit=crop&q=80',
  status: 'IN_PROGRESS',
  rules: {
    pointsForWin: 3,
    pointsForDraw: 1,
    pointsForLoss: 0,
    tiebreakers: ['POINTS', 'VICTORIES', 'GOAL_DIFFERENCE', 'GOALS_FOR', 'DIRECT_HEAD_TO_HEAD', 'FEWEST_CARDS', 'DRAW'],
    substitutionsAllowed: 7,
    matchDurationMinutes: 50, // 25x2
    startersCount: 7,
    maxBenchCount: 7,
    yellowCardsForSuspension: 3,
    directRedCardSuspensionGames: 2,
    registrationFeeAmount: 85.0,
    woGoalsGiven: 3,
  },
  createdAt: '2026-07-01T10:00:00Z',
};

export const sampleChampionships: Championship[] = [
  sampleChampionship,
  {
    id: 'champ_2',
    name: 'Torneio de Verão Amador 2026',
    slug: 'torneio-de-verao-amador-2026',
    description: 'Edição especial de verão reunindo as melhores equipes amadoras da zona sul com arbitragem federada.',
    startDate: '2026-10-01',
    endDate: '2026-11-15',
    location: 'Complexo Esportivo Morumbi',
    address: 'Rua do Estádio, 450',
    city: 'São Paulo',
    state: 'SP',
    organizerName: 'Liga Paulista de Futebol Society',
    organizerPhone: '(11) 97123-4567',
    organizerEmail: 'verao@ligasociety.com.br',
    logoUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?w=300&auto=format&fit=crop&q=80',
    status: 'REGISTRATION_OPEN',
    rules: {
      pointsForWin: 3,
      pointsForDraw: 1,
      pointsForLoss: 0,
      tiebreakers: ['POINTS', 'VICTORIES', 'GOAL_DIFFERENCE', 'GOALS_FOR', 'DIRECT_HEAD_TO_HEAD'],
      substitutionsAllowed: 5,
      matchDurationMinutes: 40,
      startersCount: 7,
      maxBenchCount: 5,
      yellowCardsForSuspension: 2,
      directRedCardSuspensionGames: 1,
      registrationFeeAmount: 100.0,
      woGoalsGiven: 3,
    },
    createdAt: '2026-07-15T10:00:00Z',
  },
  {
    id: 'champ_3',
    name: 'Liga Metropolitana Master 35+',
    slug: 'liga-metropolitana-master-35',
    description: 'Campeonato exclusivo para atletas com 35 anos ou mais. Jogos aos domingos de manhã.',
    startDate: '2026-11-01',
    endDate: '2026-12-20',
    location: 'Clube Esportivo Anhembi',
    address: 'Av. das Nações, 800',
    city: 'São Paulo',
    state: 'SP',
    organizerName: 'Associação Master Fut',
    organizerPhone: '(11) 98888-7777',
    organizerEmail: 'contato@masterfut.com.br',
    logoUrl: 'https://images.unsplash.com/photo-1517927033932-b3d18e61fb3a?w=300&auto=format&fit=crop&q=80',
    status: 'PLANNING',
    rules: {
      pointsForWin: 3,
      pointsForDraw: 1,
      pointsForLoss: 0,
      tiebreakers: ['POINTS', 'VICTORIES', 'GOAL_DIFFERENCE'],
      substitutionsAllowed: 10,
      matchDurationMinutes: 50,
      startersCount: 8,
      maxBenchCount: 8,
      yellowCardsForSuspension: 3,
      directRedCardSuspensionGames: 2,
      registrationFeeAmount: 120.0,
      woGoalsGiven: 3,
    },
    createdAt: '2026-07-20T10:00:00Z',
  },
];

export const sampleTeams: Team[] = [
  {
    id: 'team_1',
    championshipId: 'champ_1',
    name: 'Real Boleiros FC',
    shortName: 'RBO',
    primaryColor: '#1e40af', // Blue
    secondaryColor: '#f59e0b', // Amber
    coachName: 'Marcelo "Tite" Oliveira',
    captainPlayerId: 'play_1',
    managerName: 'Eduardo Costa',
  },
  {
    id: 'team_2',
    championshipId: 'champ_1',
    name: 'Vila Nova Futebol Society',
    shortName: 'VNV',
    primaryColor: '#dc2626', // Red
    secondaryColor: '#ffffff', // White
    coachName: 'Carlos Alberto',
    captainPlayerId: 'play_8',
    managerName: 'Roberto Nunes',
  },
  {
    id: 'team_3',
    championshipId: 'champ_1',
    name: 'Os Galácticos da Várzea',
    shortName: 'GAL',
    primaryColor: '#10b981', // Emerald green
    secondaryColor: '#000000', // Black
    coachName: 'Fabio "Mago" Santos',
    captainPlayerId: 'play_15',
    managerName: 'Henrique Mello',
  },
  {
    id: 'team_4',
    championshipId: 'champ_1',
    name: 'Resenha & Futebol FC',
    shortName: 'RES',
    primaryColor: '#8b5cf6', // Purple
    secondaryColor: '#facc15', // Yellow
    coachName: 'Leandro Damião',
    captainPlayerId: 'play_22',
    managerName: 'Thiago Neves',
  },
  {
    id: 'team_5',
    championshipId: 'champ_1',
    name: 'Estrela D\'Alva Esporte Clube',
    shortName: 'EDA',
    primaryColor: '#0ea5e9', // Sky blue
    secondaryColor: '#1e293b', // Slate
    coachName: 'Renato Gaúcho',
    captainPlayerId: 'play_29',
    managerName: 'Gustavo Lima',
  },
  {
    id: 'team_6',
    championshipId: 'champ_1',
    name: 'União Várzea FC',
    shortName: 'UVZ',
    primaryColor: '#f97316', // Orange
    secondaryColor: '#18181b', // Zinc
    coachName: 'Mano Menezes',
    captainPlayerId: 'play_36',
    managerName: 'Júlio César',
  },
];

export const samplePlayers: Player[] = [
  // Real Boleiros
  {
    id: 'play_1',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Lucas Gabriel Silveira',
    displayName: 'Lucas Silveira',
    nickname: 'Lucão',
    photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    birthDate: '1998-04-12',
    position: 'FORWARD',
    shirtNumber: 9,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    paymentDate: '2026-07-15',
    paymentMethod: 'PIX',
    skillLevel: 5,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 6,
      assists: 2,
      yellowCards: 1,
      redCards: 0,
      highlights: 2,
      mvpCount: 2,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_2',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Gabriel Henrique Ramos',
    displayName: 'Gabriel Ramos',
    nickname: 'Gabi',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    birthDate: '1999-08-20',
    position: 'GOALKEEPER',
    shirtNumber: 1,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    paymentDate: '2026-07-14',
    paymentMethod: 'PIX',
    skillLevel: 5,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 0,
      assists: 1,
      yellowCards: 0,
      redCards: 0,
      highlights: 1,
      mvpCount: 1,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_3',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Bruno Eduardo Ferreira',
    displayName: 'Bruno Ferreira',
    nickname: 'Brunão',
    photoUrl: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=150&auto=format&fit=crop&q=80',
    birthDate: '1995-11-03',
    position: 'DEFENDER',
    shirtNumber: 3,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    paymentDate: '2026-07-12',
    paymentMethod: 'CASH',
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 1,
      assists: 1,
      yellowCards: 2,
      redCards: 0,
      highlights: 0,
      mvpCount: 0,
      minutesPlayed: 145,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_4',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Matheus Felipe de Souza',
    displayName: 'Matheus Souza',
    nickname: 'Theus',
    photoUrl: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=150&auto=format&fit=crop&q=80',
    birthDate: '2001-02-17',
    position: 'MIDFIELDER',
    shirtNumber: 10,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    paymentDate: '2026-07-16',
    paymentMethod: 'PIX',
    skillLevel: 5,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 3,
      assists: 4,
      yellowCards: 0,
      redCards: 0,
      highlights: 1,
      mvpCount: 0,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_5',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Rodrigo Augusto Lima',
    displayName: 'Rodrigo Lima',
    nickname: 'Digão',
    position: 'WING',
    shirtNumber: 7,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 2,
      goals: 2,
      assists: 1,
      yellowCards: 1,
      redCards: 0,
      highlights: 0,
      mvpCount: 0,
      minutesPlayed: 110,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_6',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Felipe Augusto Rocha',
    displayName: 'Felipe Rocha',
    nickname: 'Felipinho',
    position: 'LEFT_BACK',
    shirtNumber: 6,
    status: 'ACTIVE',
    paymentStatus: 'PARTIAL',
    amountPaid: 50.0,
    skillLevel: 3,
    stats: {
      matchesPlayed: 3,
      starts: 2,
      goals: 0,
      assists: 2,
      yellowCards: 0,
      redCards: 0,
      highlights: 0,
      mvpCount: 0,
      minutesPlayed: 95,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_7',
    championshipId: 'champ_1',
    teamId: 'team_1',
    fullName: 'Thiago Barbosa',
    displayName: 'Thiago Barbosa',
    nickname: 'Thiagão',
    position: 'DEF_MIDFIELDER',
    shirtNumber: 5,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 1,
      assists: 0,
      yellowCards: 2,
      redCards: 0,
      highlights: 0,
      mvpCount: 0,
      minutesPlayed: 140,
      suspensionsServed: 0,
    },
  },

  // Vila Nova FC
  {
    id: 'play_8',
    championshipId: 'champ_1',
    teamId: 'team_2',
    fullName: 'Carlos Eduardo Santos',
    displayName: 'Cadu Santos',
    nickname: 'Cadu',
    photoUrl: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=150&auto=format&fit=crop&q=80',
    birthDate: '1996-09-10',
    position: 'FORWARD',
    shirtNumber: 11,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 5,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 5,
      assists: 1,
      yellowCards: 1,
      redCards: 0,
      highlights: 2,
      mvpCount: 1,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_9',
    championshipId: 'champ_1',
    teamId: 'team_2',
    fullName: 'Diego Armando Alves',
    displayName: 'Diego Alves',
    nickname: 'Muralha',
    position: 'GOALKEEPER',
    shirtNumber: 12,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 0,
      assists: 0,
      yellowCards: 0,
      redCards: 0,
      highlights: 1,
      mvpCount: 0,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_10',
    championshipId: 'champ_1',
    teamId: 'team_2',
    fullName: 'Vinicius Junior Martins',
    displayName: 'Vini Martins',
    nickname: 'Vini',
    position: 'WING',
    shirtNumber: 7,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 3,
      assists: 3,
      yellowCards: 0,
      redCards: 0,
      highlights: 1,
      mvpCount: 1,
      minutesPlayed: 140,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_11',
    championshipId: 'champ_1',
    teamId: 'team_2',
    fullName: 'Marcos Vinicius Pereira',
    displayName: 'Marcos Pereira',
    nickname: 'Marcão',
    position: 'DEFENDER',
    shirtNumber: 4,
    status: 'ACTIVE',
    paymentStatus: 'UNPAID',
    amountPaid: 0,
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 0,
      assists: 0,
      yellowCards: 3, // Pendurado / Suspenso próx
      redCards: 0,
      highlights: 0,
      mvpCount: 0,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },

  // Os Galácticos
  {
    id: 'play_15',
    championshipId: 'champ_1',
    teamId: 'team_3',
    fullName: 'Everton Ribeiro da Silva',
    displayName: 'Everton Ribeiro',
    nickname: 'Mago',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=150&auto=format&fit=crop&q=80',
    birthDate: '1994-06-25',
    position: 'ATT_MIDFIELDER',
    shirtNumber: 10,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 5,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 4,
      assists: 5,
      yellowCards: 0,
      redCards: 0,
      highlights: 3,
      mvpCount: 2,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_16',
    championshipId: 'champ_1',
    teamId: 'team_3',
    fullName: 'Marcelo Moreno',
    displayName: 'Marcelo Moreno',
    nickname: 'Matador',
    position: 'FORWARD',
    shirtNumber: 9,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 4,
      assists: 1,
      yellowCards: 1,
      redCards: 0,
      highlights: 1,
      mvpCount: 0,
      minutesPlayed: 135,
      suspensionsServed: 0,
    },
  },
  {
    id: 'play_17',
    championshipId: 'champ_1',
    teamId: 'team_3',
    fullName: 'Jailson de Oliveira',
    displayName: 'Jailson Oliveira',
    nickname: 'Paredão',
    position: 'GOALKEEPER',
    shirtNumber: 1,
    status: 'ACTIVE',
    paymentStatus: 'EXEMPT',
    amountPaid: 0,
    skillLevel: 5,
    stats: {
      matchesPlayed: 3,
      starts: 3,
      goals: 0,
      assists: 0,
      yellowCards: 0,
      redCards: 0,
      highlights: 2,
      mvpCount: 1,
      minutesPlayed: 150,
      suspensionsServed: 0,
    },
  },

  // Free Agents / Unassigned players for Draft Module
  {
    id: 'play_40',
    championshipId: 'champ_1',
    teamId: null,
    fullName: 'Alexandre Pato de Souza',
    displayName: 'Alex Pato',
    nickname: 'Pato',
    photoUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    birthDate: '2000-01-10',
    position: 'FORWARD',
    shirtNumber: 11,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 5,
    stats: { matchesPlayed: 0, starts: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, highlights: 0, mvpCount: 0, minutesPlayed: 0, suspensionsServed: 0 },
  },
  {
    id: 'play_41',
    championshipId: 'champ_1',
    teamId: null,
    fullName: 'Claudio Taffarel Neves',
    displayName: 'Claudio Taffarel',
    nickname: 'Goleirasso',
    position: 'GOALKEEPER',
    shirtNumber: 12,
    status: 'ACTIVE',
    paymentStatus: 'UNPAID',
    amountPaid: 0,
    skillLevel: 5,
    stats: { matchesPlayed: 0, starts: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, highlights: 0, mvpCount: 0, minutesPlayed: 0, suspensionsServed: 0 },
  },
  {
    id: 'play_42',
    championshipId: 'champ_1',
    teamId: null,
    fullName: 'David Luiz Moreira',
    displayName: 'David Luiz',
    nickname: 'David',
    position: 'DEFENDER',
    shirtNumber: 23,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: { matchesPlayed: 0, starts: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, highlights: 0, mvpCount: 0, minutesPlayed: 0, suspensionsServed: 0 },
  },
  {
    id: 'play_43',
    championshipId: 'champ_1',
    teamId: null,
    fullName: 'Gerson Canhota Lima',
    displayName: 'Gerson Canhota',
    nickname: 'Canhota',
    position: 'MIDFIELDER',
    shirtNumber: 8,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 4,
    stats: { matchesPlayed: 0, starts: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, highlights: 0, mvpCount: 0, minutesPlayed: 0, suspensionsServed: 0 },
  },
  {
    id: 'play_44',
    championshipId: 'champ_1',
    teamId: null,
    fullName: 'Júnior Baiano Santos',
    displayName: 'Júnior Baiano',
    nickname: 'Baiano',
    position: 'DEFENDER',
    shirtNumber: 3,
    status: 'ACTIVE',
    paymentStatus: 'UNPAID',
    amountPaid: 0,
    skillLevel: 3,
    stats: { matchesPlayed: 0, starts: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, highlights: 0, mvpCount: 0, minutesPlayed: 0, suspensionsServed: 0 },
  },
  {
    id: 'play_45',
    championshipId: 'champ_1',
    teamId: null,
    fullName: 'Roberto Carlos da Silva',
    displayName: 'Roberto Carlos',
    nickname: 'Chute de Aço',
    position: 'LEFT_BACK',
    shirtNumber: 6,
    status: 'ACTIVE',
    paymentStatus: 'PAID',
    amountPaid: 85.0,
    skillLevel: 5,
    stats: { matchesPlayed: 0, starts: 0, goals: 0, assists: 0, yellowCards: 0, redCards: 0, highlights: 0, mvpCount: 0, minutesPlayed: 0, suspensionsServed: 0 },
  },
];

export const samplePhases: Phase[] = [
  {
    id: 'phase_1',
    championshipId: 'champ_1',
    name: 'Fase de Grupos',
    type: 'GROUPS',
    order: 1,
    groupsCount: 2,
    teamsPerGroup: 3,
    qualifiedPerGroup: 2,
    roundsCount: 3,
    isTwoLegged: false,
    completed: false,
  },
  {
    id: 'phase_2',
    championshipId: 'champ_1',
    name: 'Semifinais & Final',
    type: 'KNOCKOUT',
    order: 2,
    isTwoLegged: false,
    completed: false,
  },
];

export const sampleGroups: Group[] = [
  {
    id: 'group_A',
    phaseId: 'phase_1',
    name: 'Grupo A',
    teamIds: ['team_1', 'team_2', 'team_3'],
  },
  {
    id: 'group_B',
    phaseId: 'phase_1',
    name: 'Grupo B',
    teamIds: ['team_4', 'team_5', 'team_6'],
  },
];

export const sampleMatches: Match[] = [
  // Finished matches - Rodada 1
  {
    id: 'match_101',
    championshipId: 'champ_1',
    phaseId: 'phase_1',
    groupId: 'group_A',
    roundNumber: 1,
    homeTeamId: 'team_1', // Real Boleiros
    awayTeamId: 'team_2', // Vila Nova
    homeScore: 4,
    awayScore: 3,
    date: '2026-08-01',
    time: '14:00',
    location: 'Arena Park - Campo 1',
    referee: 'Sandro Meira Ricci',
    status: 'FINISHED',
    currentMinute: 50,
    mvpPlayerId: 'play_1',
    notes: 'Jogo eletrizante com virada no último minuto!',
  },
  {
    id: 'match_102',
    championshipId: 'champ_1',
    phaseId: 'phase_1',
    groupId: 'group_B',
    roundNumber: 1,
    homeTeamId: 'team_4', // Resenha
    awayTeamId: 'team_5', // Estrela D'Alva
    homeScore: 2,
    awayScore: 2,
    date: '2026-08-01',
    time: '15:15',
    location: 'Arena Park - Campo 1',
    referee: 'Márcio Rezende',
    status: 'FINISHED',
    currentMinute: 50,
    mvpPlayerId: 'play_15',
  },

  // Finished matches - Rodada 2
  {
    id: 'match_103',
    championshipId: 'champ_1',
    phaseId: 'phase_1',
    groupId: 'group_A',
    roundNumber: 2,
    homeTeamId: 'team_3', // Galácticos
    awayTeamId: 'team_1', // Real Boleiros
    homeScore: 3,
    awayScore: 3,
    date: '2026-08-03',
    time: '19:30',
    location: 'Arena Park - Campo 1',
    referee: 'Wilton Pereira Sampaio',
    status: 'FINISHED',
    currentMinute: 50,
    mvpPlayerId: 'play_15',
  },
  {
    id: 'match_104',
    championshipId: 'champ_1',
    phaseId: 'phase_1',
    groupId: 'group_B',
    roundNumber: 2,
    homeTeamId: 'team_6', // União Várzea
    awayTeamId: 'team_4', // Resenha
    homeScore: 1,
    awayScore: 4,
    date: '2026-08-03',
    time: '20:45',
    location: 'Arena Park - Campo 2',
    referee: 'Anderson Daronco',
    status: 'FINISHED',
    currentMinute: 50,
  },

  // LIVE MATCH IN PROGRESS! Perfect for live operator mode testing!
  {
    id: 'match_105',
    championshipId: 'champ_1',
    phaseId: 'phase_1',
    groupId: 'group_A',
    roundNumber: 3,
    homeTeamId: 'team_2', // Vila Nova FC
    awayTeamId: 'team_3', // Galácticos
    homeScore: 2,
    awayScore: 1,
    date: '2026-08-05',
    time: '09:00',
    location: 'Arena Park - Campo 1',
    referee: 'Raphael Claus',
    status: 'IN_PROGRESS',
    currentMinute: 34,
    halfTime: '2ND',
    notes: 'Partida em andamento transmitida ao vivo.',
  },

  // Scheduled future matches
  {
    id: 'match_106',
    championshipId: 'champ_1',
    phaseId: 'phase_1',
    groupId: 'group_B',
    roundNumber: 3,
    homeTeamId: 'team_5',
    awayTeamId: 'team_6',
    homeScore: 0,
    awayScore: 0,
    date: '2026-08-08',
    time: '16:00',
    location: 'Arena Park - Campo 1',
    referee: 'Pricilla Silva',
    status: 'SCHEDULED',
  },

  // Semi-Final 1 (Knockout)
  {
    id: 'match_201',
    championshipId: 'champ_1',
    phaseId: 'phase_2',
    roundNumber: 1,
    homeTeamId: 'team_1', // 1º Grupo A
    awayTeamId: 'team_4', // 2º Grupo B
    homeScore: 0,
    awayScore: 0,
    date: '2026-08-15',
    time: '10:00',
    location: 'Arena Park - Campo Principal',
    status: 'SCHEDULED',
    notes: 'Semifinal 1',
  },
  {
    id: 'match_202',
    championshipId: 'champ_1',
    phaseId: 'phase_2',
    roundNumber: 1,
    homeTeamId: 'team_2', // 2º Grupo A
    awayTeamId: 'team_5', // 1º Grupo B
    homeScore: 0,
    awayScore: 0,
    date: '2026-08-15',
    time: '11:30',
    location: 'Arena Park - Campo Principal',
    status: 'SCHEDULED',
    notes: 'Semifinal 2',
  },
];

export const sampleEvents: MatchEvent[] = [
  // match_101 events
  { id: 'ev_1', matchId: 'match_101', teamId: 'team_1', type: 'GOAL', playerId: 'play_1', minute: 12, createdAt: '2026-08-01T14:12:00Z' },
  { id: 'ev_2', matchId: 'match_101', teamId: 'team_2', type: 'GOAL', playerId: 'play_8', minute: 18, createdAt: '2026-08-01T14:18:00Z' },
  { id: 'ev_3', matchId: 'match_101', teamId: 'team_1', type: 'GOAL', playerId: 'play_4', minute: 24, createdAt: '2026-08-01T14:24:00Z' },
  { id: 'ev_4', matchId: 'match_101', teamId: 'team_2', type: 'GOAL', playerId: 'play_8', minute: 31, createdAt: '2026-08-01T14:31:00Z' },
  { id: 'ev_5', matchId: 'match_101', teamId: 'team_2', type: 'GOAL', playerId: 'play_10', minute: 40, createdAt: '2026-08-01T14:40:00Z' },
  { id: 'ev_6', matchId: 'match_101', teamId: 'team_1', type: 'GOAL', playerId: 'play_1', minute: 45, createdAt: '2026-08-01T14:45:00Z' },
  { id: 'ev_7', matchId: 'match_101', teamId: 'team_1', type: 'GOAL', playerId: 'play_1', minute: 49, createdAt: '2026-08-01T14:49:00Z' },
  { id: 'ev_8', matchId: 'match_101', teamId: 'team_2', type: 'YELLOW_CARD', playerId: 'play_11', minute: 35, reason: 'Falta tática', createdAt: '2026-08-01T14:35:00Z' },

  // match_105 (Live Match Events)
  { id: 'ev_20', matchId: 'match_105', teamId: 'team_2', type: 'GOAL', playerId: 'play_8', minute: 14, createdAt: '2026-08-05T09:14:00Z' },
  { id: 'ev_21', matchId: 'match_105', teamId: 'team_3', type: 'GOAL', playerId: 'play_15', minute: 22, createdAt: '2026-08-05T09:22:00Z' },
  { id: 'ev_22', matchId: 'match_105', teamId: 'team_2', type: 'GOAL', playerId: 'play_10', minute: 31, createdAt: '2026-08-05T09:31:00Z' },
  { id: 'ev_23', matchId: 'match_105', teamId: 'team_2', type: 'YELLOW_CARD', playerId: 'play_11', minute: 28, reason: 'Reclamação', createdAt: '2026-08-05T09:28:00Z' },
];

export const sampleSuspensions: Suspension[] = [
  {
    id: 'susp_1',
    championshipId: 'champ_1',
    playerId: 'play_11',
    playerName: 'Marcos Pereira',
    teamName: 'Vila Nova FC',
    matchId: 'match_105',
    gamesCount: 1,
    gamesServed: 0,
    reason: 'Acúmulo de 3 Cartões Amarelos',
    active: true,
    createdAt: '2026-08-05T09:30:00Z',
  },
];

export const sampleAuditLogs: AuditLog[] = [
  {
    id: 'log_1',
    championshipId: 'champ_1',
    userId: 'usr_admin_1',
    userName: 'Rodrigo Silva',
    action: 'MATCH_STARTED',
    entity: 'Match',
    entityId: 'match_105',
    details: 'Iniciou a partida Vila Nova FC x Os Galácticos ao vivo.',
    timestamp: '2026-08-05T09:00:00Z',
  },
  {
    id: 'log_2',
    championshipId: 'champ_1',
    userId: 'usr_admin_1',
    userName: 'Rodrigo Silva',
    action: 'GOAL_REGISTERED',
    entity: 'MatchEvent',
    entityId: 'ev_22',
    details: 'Registrou gol de Vini Martins (Vila Nova FC) aos 31 min.',
    timestamp: '2026-08-05T09:31:00Z',
  },
  {
    id: 'log_3',
    championshipId: 'champ_1',
    userId: 'usr_admin_1',
    userName: 'Rodrigo Silva',
    action: 'PAYMENT_UPDATED',
    entity: 'Player',
    entityId: 'play_1',
    details: 'Confirmou pagamento de R$ 85,00 via PIX para Lucas Silveira.',
    timestamp: '2026-07-15T14:20:00Z',
  },
];

export const sampleNotifications: NotificationItem[] = [
  {
    id: 'notif_1',
    title: 'Partida Ao Vivo!',
    message: 'Vila Nova FC 2 x 1 Os Galácticos está acontecendo agora no Campo 1.',
    type: 'INFO',
    timestamp: '2026-08-05T09:00:00Z',
    read: false,
  },
  {
    id: 'notif_2',
    title: 'Jogador Suspenso',
    message: 'Marcos Pereira (Vila Nova FC) completou 3 cartões amarelos e está suspenso para a próxima rodada.',
    type: 'WARNING',
    timestamp: '2026-08-05T09:29:00Z',
    read: false,
  },
  {
    id: 'notif_3',
    title: 'Súmula Pronta',
    message: 'Súmula oficial da partida Real Boleiros 4 x 3 Vila Nova FC já pode ser baixada em PDF.',
    type: 'SUCCESS',
    timestamp: '2026-08-01T15:00:00Z',
    read: true,
  },
];
